# Generated by Django 5.2.6 on 2025-11-19 16:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad_disponible', models.IntegerField()),
                ('unidad', models.CharField(choices=[('unidades', 'Unidades'), ('metros', 'Metros'), ('litros', 'Litros'), ('kilos', 'Kilos')], default='unidades', max_length=20)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('red_social', models.CharField(blank=True, max_length=100)),
                ('descripcion_diseno', models.TextField()),
                ('fecha_requerida', models.DateField(blank=True, null=True)),
                ('plataforma', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('sitio_web', 'Sitio Web'), ('presencial', 'Presencial'), ('otro', 'Otro')], default='sitio_web', max_length=20)),
                ('estado_pedido', models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('en_proceso', 'En proceso'), ('realizado', 'Realizado'), ('entregado', 'Entregado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('token_seguimiento', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('presupuesto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notas_internas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='referencias/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_referencia', to='tienda.pedido')),
            ],
            options={
                'verbose_name': 'Imagen de Referencia',
                'verbose_name_plural': 'Imágenes de Referencia',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('imagen_1', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='producto_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.producto'),
        ),
    ]
