# Generated by Django 5.2.8 on 2025-11-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='token_seguimiento',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
