# Generated by Django 5.2.8 on 2025-11-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_pedido_token_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='token_seguimiento',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True, verbose_name='Token de seguimiento'),
        ),
    ]
