# Generated by Django 6.0 on 2025-12-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_alter_pedido_token_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='color',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='presupuesto_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Presupuesto estimado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='notas_internas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='red_social',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='token_seguimiento',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
