# Generated by Django 6.0 on 2025-12-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0004_insumo_color_insumo_marca_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="imagen_1",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/productos/"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen_2",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/productos/"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="imagen_3",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/productos/"
            ),
        ),
    ]
